### PR TITLE
Form page

### PR DESCRIPTION
**Pull request by denesnori**

### CODE REVIEW

**Comment by esraajb** [comment]
@denesnori please, make sure you add labels :)

waiting for @SavageWilliam approval

**Comment by denesnori** [comment]
Ups..I totally forgot that i should have added labels too.

(Please note that I have comments in my code on purpose. Please no :fire:  ;D )

**Comment by denesnori** [comment]
Our POs have just sent us some content for this page. I update the page and push again :)

**Comment by esraajb** [comment]
cool.
please, assign me again when you are done.

**Pull request merged**
